
version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: react-backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-database
    ports:
      - "27017:27017"
    volumes:
      - ./mongo backup:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
